### ISSUE TITLE
Direct Pay demo gif has been deleted

### ISSUE THREAD

**Issue by babogoos** [TapPay/tappay-android-example#3]
On the README.md, 
The Direct Pay demo gif has been deleted by Giphy,
(https://giphy.com/media/xUOxf4aa0035sXkfeg/giphy.gif)
Please renew link or put a offline gif file like Google Pay demo.

Sincerely yours,
Dion

**Comment by cherrigaryhsu** [comment]
Hi @babogoos 

Thanks your feedback, we will fix it.

**Comment by cherrigaryhsu** [comment]
Hi @babogoos 

Since we fix this in the lastest commit , close this issue.
