### ISSUE TITLE
帳款服務程式庫 3

### ISSUE THREAD

**Issue by jayceeok** [TapPay/tappay-android-example#5]
谷歌開發者郵件中提到"自 2021 年 8 月 2 日起，所有新應用程式都必須採用 Google Play 帳款服務程式庫 3 或以上版本。
自 2021 年 11 月 1 日起，現有應用程式的所有更新都必須採用 Google Play 帳款服務程式庫 3 或以上版本。"，請問這個帳款服務程式庫 3是集成在tappay的jar裡面了嗎？

**Comment by cherrigaryhsu** [comment]
Hi @jayceeok 

關於google pay 相關設定請參考

官方文件 https://developers.google.com/pay/api/android/guides/setup
我們的README https://github.com/TapPay/tappay-android-example#google-pay
