### ISSUE TITLE
Got "Entry name 'AndroidManifest.xml' collided" when using 3.2.0

### ISSUE THREAD

**Issue by ghlin-daniel** [TapPay/tappay-android-example#6]
Not sure if that's intended. 3.2.0 includes AndroidManifext.xml which causes "Entry name 'AndroidManifest.xml' collided".
Checked 3.0.0 and it didn't have this issue.

**Comment by dh46tw** [comment]
I also encountered this error while implementing the newer version 3.3.0.
I'm wondering if there is any solution to this error?

**Comment by HSTsou** [comment]
I also got this error on version 3.3.0.

**Comment by ghlin-daniel** [comment]
https://github.com/TapPay/tappay-android-example/releases/tag/3.3.2
@dh-46 @HSTsou It seems fixed but I didn't test it.

**Comment by cherrigaryhsu** [comment]
Hi @ghlin-daniel @dh-46 @HSTsou ,

Did you still encounter this issue with our newest version?

(ex: 3.8.2)

**Comment by cherrigaryhsu** [comment]
Since no one is following , we close this issue
